"""Concrete sample exercises, not claims of universal PDF compatibility."""
PDF_EXAMPLES = {
    'index': ('Merge two halves', 'Split the four-page practice PDF after page 2. Add the two resulting PDFs to Merge in their original order.', 'The result should have four pages: Cover, Checklist, Notes, Appendix. If Notes comes first, reverse the input order. Do not add the original packet as a third input.', 'Merging does not certify preservation of digital signatures, forms or bookmarks.'),
    'pdf_split': ('One cut, two documents', 'Load the four-page practice PDF. Select only the cut between pages 2 and 3.', 'The ZIP should contain two PDFs with two pages each: Cover/Checklist and Notes/Appendix. Extra files usually mean additional cut markers were selected.', 'Splitting is not redaction or password removal. Retained pages still contain their original information.'),
    'pdf_organizer': ('Keep Notes, then Cover', 'Load the practice PDF. Remove pages 2 and 4. Move Notes before Cover and rotate Notes once. Choose SAVE PDF.', 'Expect two pages: Notes rotated 90 degrees clockwise, then Cover unchanged. Selecting only Notes and using EXTRACT SELECTED should produce one page. Page labels refer to original source numbers.', 'There is no complete undo history: reload the original if a page was removed by mistake. This sample does not test forms, bookmarks or signatures.'),
    'pdf_annotations': ('Save and reopen a review note', 'Load the practice PDF. Choose COMMENT, click beside the body text on Cover, enter Review page order, and download the PDF. Reopen the download in this tool to inspect the note.', 'The note text should remain editable. Add a highlight over dark text on the white area; a highlight over the dark header can look almost black. Check the recipient reader too: some readers show a note icon without opening its text.', 'Highlights are rectangular overlays, not redaction. They do not remove underlying text. Existing appearance streams and less common annotation types may behave differently across readers; keep the original.'),
    'pdf_to_images': ('Export pages 1 and 3', 'Load the practice PDF, enter 1, 3, select PNG and 1× scale, then download the ZIP.', 'Expect page-001.png (Cover) and page-003.png (Notes), each 612 × 792 pixels. Four preview cards do not mean all four pages will be exported.', 'Rendered images do not preserve selectable text, interactive forms or editable comments. Check which annotations appear in the rendered output.'),
    'images_to_pdf': ('Put the two exported PNGs into a PDF', 'Export pages 1 and 3 using PDF to Images first. Add those PNGs here with Cover before Notes. Select US Letter and a small margin.', 'Expect two 612 × 792-point pages, Cover then Notes, with the complete images inside the margins. Swap the input order if the result starts with Notes.', 'This makes image-based PDF pages, not OCR text. A larger page or image does not restore detail missing from the source.'),
}
