"""Search-oriented, user-visible guides for each Browser Tools utility."""

TOOL_SEO = {
    "index": {
        "name": "Private PDF Merger",
        "h1": "FREE PDF MERGER.",
        "intro": "Merge PDF files for free, with no daily usage limits. Arrange documents in your chosen order. No account or file uploads required.",
        "title": "Free PDF Merger — Combine PDF Files, No Sign-Up",
        "description": "Merge PDF files for free, with no daily usage limits. Arrange documents in your chosen order. No account or file uploads required.",
        "heading": "HOW TO MERGE PDF FILES",
        "summary": "Combine two or more PDF documents in the order you choose. Processing happens in browser memory, so the source files are not uploaded to an application server.",
        "steps": ["Add at least two PDF files.", "Use the arrow controls to arrange the documents.", "Remove any file you do not want in the result.", "Select MERGE and save the downloaded PDF."],
        "notes": [
            ("LOCAL PDF PROCESSING", "The browser reads the selected documents and builds the new PDF on your device. Available memory, document size, and page count can affect processing time."),
            ("BEFORE YOU DELETE ORIGINALS", "Open the downloaded file and confirm its page order, orientation, links, forms, and visual quality. Keep backup copies of important source documents."),
        ],
        "faq": [
            ("Are my PDF files uploaded?", "No. This tool does not submit selected PDFs to an application upload endpoint."),
            ("Can I change the file order?", "Yes. Arrange the files in the queue before selecting MERGE."),
            ("Why can a large merge take longer?", "The work uses your device's processor and memory. Large or complex PDFs require more local resources."),
        ],
        "related": [("pdf_split", "SPLIT PDF"), ("pdf_organizer", "ORGANIZE PAGES"), ("pdf_to_images", "PDF TO IMAGES")],
    },
    "pdf_split": {
        "name": "Private PDF Splitter",
        "h1": "FREE PDF SPLITTER.",
        "intro": "Split PDFs for free, with no daily usage limits. No account or file uploads required.",
        "title": "Free Unlimited PDF Splitter — No Sign-Up, No Uploads",
        "description": "Split PDFs for free, with no daily usage limits. No account or file uploads required.",
        "heading": "HOW TO SPLIT A PDF",
        "summary": "See each page before choosing boundaries. A cut marker separates the pages on its left and right into different output documents.",
        "steps": ["Add one PDF file.", "Review the page thumbnails in reading order.", "Select the cut lines where a new document should begin.", "Choose SPLIT & DOWNLOAD ZIP and inspect the results."],
        "notes": [
            ("CHOOSE CUT POINTS CAREFULLY", "Cut controls appear at document boundaries and between pages. Clear or select all cuts when you need to reset the layout quickly."),
            ("PRIVATE BY DESIGN", "Previewing, splitting, and packaging happen locally. The source document is not stored by this site."),
        ],
        "faq": [
            ("Is PDF splitting free and unlimited?", "Yes. There is no daily usage quota. Unlimited refers to the number of uses, not file size: available device memory and browser performance limit the documents you can process."),
            ("Can I split a PDF into every page?", "Yes. Use SELECT ALL to place a cut between every page."),
            ("What does the ZIP contain?", "It contains the PDF sections created by your selected cut points."),
            ("Can encrypted PDFs be split?", "Password-protected or restricted documents may not open. Use a permitted, unlocked copy."),
        ],
        "related": [("index", "MERGE PDF"), ("pdf_organizer", "ORGANIZE PAGES"), ("pdf_to_images", "PDF TO IMAGES")],
    },
    "pdf_organizer": {
        "name": "PDF Page Organizer",
        "h1": "FREE PDF ORGANIZER.",
        "intro": "Reorder, rotate, delete or extract PDF pages for free, with no daily usage limits. No account or file uploads required.",
        "title": "Free PDF Organizer — Reorder, Rotate & Extract Pages",
        "description": "Reorder, rotate, delete or extract PDF pages for free, with no daily usage limits. No account or file uploads required.",
        "heading": "ORGANIZE PDF PAGES",
        "summary": "Edit the page sequence of one PDF before creating a new document. Page cards can be dragged, rotated, removed, or selected for extraction.",
        "steps": ["Add one PDF and wait for the thumbnails.", "Drag page cards into the required order.", "Rotate or remove pages as needed.", "Save all visible pages, or select pages and use EXTRACT SELECTED."],
        "notes": [
            ("SAVE OR EXTRACT", "SAVE PDF keeps every visible page in the displayed order. EXTRACT SELECTED creates a separate PDF containing only the pages you selected."),
            ("NON-DESTRUCTIVE WORKFLOW", "The original file is not overwritten. The organizer creates a new download so you can compare it with the source."),
        ],
        "faq": [
            ("Can I undo a removed page?", "There is no full undo history. Reload the source PDF if you remove a page by mistake."),
            ("Does rotation change the original?", "No. Rotation is applied only to the new downloaded PDF."),
            ("Can I combine several PDFs here?", "Use PDF Merge for multiple documents; this organizer works with one PDF at a time."),
        ],
        "related": [("pdf_annotations", "PDF ANNOTATIONS"), ("index", "MERGE PDF"), ("pdf_split", "SPLIT PDF")],
    },
    "pdf_annotations": {
        "name": "Private PDF Annotation Editor",
        "h1": "FREE PDF ANNOTATION EDITOR.",
        "intro": "Add or edit PDF highlights and comments for free, with no daily usage limits. No account or file uploads required.",
        "title": "Free PDF Annotation Editor — Highlights & Comments",
        "description": "Add or edit PDF highlights and comments for free, with no daily usage limits. No account or file uploads required.",
        "heading": "EDIT PDF HIGHLIGHTS AND COMMENTS",
        "summary": "Review existing highlight and note annotations in one place. Add rectangular highlights or comment pins, edit their text and color, and save a new annotated PDF in your browser.",
        "steps": ["Add one PDF file.", "Click an existing highlight or comment to inspect and edit it.", "Choose HIGHLIGHT and drag, or choose COMMENT and click the page.", "Download a new PDF containing the updated annotations."],
        "notes": [
            ("CLICKABLE PDF ANNOTATIONS", "Highlights and comment pins are saved as standard PDF annotations so compatible PDF readers can display and open them."),
            ("LOCAL AND NON-DESTRUCTIVE", "The source PDF remains on your device and is not overwritten. The editor creates a separate downloadable copy."),
        ],
        "faq": [
            ("Are existing comments supported?", "Yes. The editor finds comments attached to highlights, text notes, shapes, stamps, ink, and other common PDF annotations, then lists them by page for quick review."),
            ("Can I highlight exact text?", "Drag a rectangle across the line or area you want to mark. The first version creates rectangular highlights rather than selecting individual text glyphs."),
            ("Is the PDF uploaded?", "No. Reading, editing, and saving happen locally in your browser."),
        ],
        "related": [("pdf_organizer", "ORGANIZE PAGES"), ("pdf_split", "SPLIT PDF"), ("index", "MERGE PDF")],
    },
    "pdf_to_images": {
        "name": "PDF to Image Converter",
        "h1": "FREE PDF TO IMAGE CONVERTER.",
        "intro": "Convert PDF pages to JPG or PNG for free, with no daily usage limits. Choose pages and download a ZIP. No account or file uploads required.",
        "title": "Free PDF to JPG & PNG Converter — No Uploads",
        "description": "Convert PDF pages to JPG or PNG for free, with no daily usage limits. Choose pages and download a ZIP. No account or file uploads required.",
        "heading": "CONVERT PDF TO IMAGES",
        "summary": "Render an entire PDF or selected pages as PNG or JPEG files. Page-range controls help avoid processing pages you do not need.",
        "steps": ["Add one PDF.", "Enter a range such as 1-3, 5 or leave it blank for all pages.", "Choose PNG or JPEG and a rendering scale.", "Download the generated images as a ZIP."],
        "notes": [
            ("PNG OR JPEG", "PNG is useful for text, diagrams, and crisp edges. JPEG can produce smaller photographic files and offers an adjustable quality setting."),
            ("SCALE AND MEMORY", "A larger rendering scale creates more pixels and can improve detail, but it also increases file size, memory use, and processing time."),
        ],
        "faq": [
            ("Can I convert only one page?", "Yes. Enter that page number in the page-range field."),
            ("Why are the results in a ZIP?", "A ZIP keeps multiple page images together in one download."),
            ("Does this extract original embedded images?", "No. It renders each complete PDF page as an image."),
        ],
        "related": [("images_to_pdf", "IMAGES TO PDF"), ("pdf_organizer", "ORGANIZE PAGES"), ("image_toolkit", "IMAGE TOOLKIT")],
    },
    "images_to_pdf": {
        "name": "Images to PDF Converter",
        "h1": "FREE IMAGES TO PDF CONVERTER.",
        "intro": "Convert JPG, PNG or WebP images to PDF for free, with no daily usage limits. Arrange images before saving. No account or file uploads required.",
        "title": "Free JPG, PNG & WebP to PDF Converter",
        "description": "Convert JPG, PNG or WebP images to PDF for free, with no daily usage limits. Arrange images before saving. No account or file uploads required.",
        "heading": "CONVERT IMAGES TO PDF",
        "summary": "Turn a sequence of JPG, PNG, or WebP images into one downloadable PDF. Reorder the images and select how each image fits on its page.",
        "steps": ["Add one or more supported images.", "Arrange or remove image cards.", "Choose matched image pages, A4, or US Letter and set a margin.", "Select CREATE PDF and review the download."],
        "notes": [
            ("PAGE SIZE OPTIONS", "Match each image preserves its natural proportions. A4 and US Letter place images inside a consistent portrait page."),
            ("IMAGE QUALITY", "The tool places the selected image data into the new document. Very large images can create a large PDF and require more browser memory."),
        ],
        "faq": [
            ("Which image formats are supported?", "The file picker accepts JPEG, PNG, and WebP images."),
            ("Can every page use the image's own size?", "Yes. Choose Match each image."),
            ("Are my images uploaded?", "No. They are read and converted in your browser."),
        ],
        "related": [("pdf_to_images", "PDF TO IMAGES"), ("image_toolkit", "IMAGE TOOLKIT"), ("index", "MERGE PDF")],
    },
    "image_toolkit": {
        "name": "Image Resizer and Converter",
        "h1": "FREE IMAGE RESIZER & CONVERTER.",
        "intro": "Resize, compress and convert JPG, PNG or WebP images for free, with no daily usage limits. No account or file uploads required.",
        "title": "Free Image Resizer & Compressor — JPG, PNG, WebP",
        "description": "Resize, compress and convert JPG, PNG or WebP images for free, with no daily usage limits. No account or file uploads required.",
        "heading": "RESIZE AND CONVERT IMAGES",
        "summary": "Prepare one image for sharing, websites, documents, or storage. Set exact pixel dimensions and download it as JPEG, PNG, or WebP.",
        "steps": ["Add a JPG, PNG, or WebP image.", "Enter the required width or height.", "Keep the aspect ratio on unless you intentionally want stretching.", "Choose a format and quality, then process the download."],
        "notes": [
            ("FORMAT DIFFERENCES", "JPEG is widely compatible and efficient for photos. PNG preserves transparency and sharp graphics. WebP often balances quality and smaller file size in modern browsers."),
            ("TRANSPARENCY", "PNG and WebP can preserve transparent areas. JPEG has no alpha channel, so transparent pixels are placed on white."),
        ],
        "faq": [
            ("Does quality affect PNG?", "No. The quality slider applies to lossy formats such as JPEG and WebP; PNG output is lossless."),
            ("What does aspect ratio mean?", "It is the relationship between width and height. Locking it prevents accidental distortion."),
            ("Can I enlarge a small image?", "Yes, but enlargement cannot recreate detail that was not present in the source."),
        ],
        "related": [("image_transform", "IMAGE TRANSFORM"), ("images_to_pdf", "IMAGES TO PDF"), ("pdf_to_images", "PDF TO IMAGES")],
    },
    "image_transform": {
        "name": "Image Mirror, Flip and Rotate Tool",
        "h1": "FREE IMAGE ROTATOR & FLIPPER.",
        "intro": "Rotate, mirror or flip images for free, with no daily usage limits. Download JPG, PNG or WebP results. No account or file uploads required.",
        "title": "Free Image Rotator & Flipper — Mirror Images Online",
        "description": "Rotate, mirror or flip images for free, with no daily usage limits. Download JPG, PNG or WebP results. No account or file uploads required.",
        "heading": "MIRROR, FLIP AND ROTATE IMAGES",
        "summary": "Correct image orientation or create a mirrored copy without uploading the original. Use quick 90-degree controls or fine-tune the angle before downloading.",
        "steps": ["Add a JPG, PNG, or WebP image.", "Mirror it horizontally, flip it vertically, or rotate it.", "Use the angle slider for precise adjustments.", "Choose an output format and download the transformed image."],
        "notes": [
            ("NON-DESTRUCTIVE EDITING", "The original file is never overwritten. Reset returns the preview to its starting orientation, and download creates a new file."),
            ("ROTATED IMAGE SIZE", "Rotating at an angle other than 90 degrees expands the output canvas so the image is not cropped. Transparent corners are preserved in PNG and WebP."),
        ],
        "faq": [
            ("What is the difference between mirror and flip?", "Mirror reverses the image from left to right. Flip turns it upside down from top to bottom."),
            ("Are my images uploaded?", "No. Loading, transforming, and exporting happen in your browser."),
            ("Which output format should I use?", "PNG preserves transparent corners. JPEG fills transparent areas with white. WebP can preserve transparency with a smaller file size."),
        ],
        "related": [("image_toolkit", "IMAGE TOOLKIT"), ("images_to_pdf", "IMAGES TO PDF"), ("pdf_to_images", "PDF TO IMAGES")],
    },
    "file_hash": {
        "name": "File Hash Checker",
        "h1": "FREE FILE HASH CHECKER.",
        "intro": "Calculate SHA-256, SHA-384 or SHA-512 checksums for free, with no daily usage limits. No account or file uploads required.",
        "title": "Free File Hash Checker — SHA-256, SHA-384, SHA-512",
        "description": "Calculate SHA-256, SHA-384 or SHA-512 checksums for free, with no daily usage limits. No account or file uploads required.",
        "heading": "CHECK A FILE CHECKSUM",
        "summary": "Calculate a repeatable cryptographic fingerprint for any local file. Compare the result with a checksum published by a trusted source.",
        "steps": ["Choose the file you want to verify.", "Select SHA-256, SHA-384, or SHA-512.", "Wait for the hexadecimal hash to appear.", "Copy it and compare every character with the trusted reference."],
        "notes": [
            ("WHAT A MATCH MEANS", "A matching checksum supports the conclusion that your copy has the same bytes as the reference file. Even a one-byte change produces a different result."),
            ("NOT A MALWARE SCAN", "A hash does not inspect a file for malicious behavior and cannot prove that the publisher is trustworthy. Obtain reference hashes from an authoritative source."),
        ],
        "faq": [
            ("Which algorithm should I choose?", "Use the algorithm named by the file publisher. SHA-256 is a common modern default when a choice is available."),
            ("Is the selected file uploaded?", "No. The browser's cryptographic API reads it locally."),
            ("Why does my hash not match?", "The file may be incomplete, modified, a different version, or compared with the wrong algorithm."),
        ],
        "related": [],
    },
    "qr_generator": {
        "name": "Private QR Code Generator",
        "h1": "FREE QR CODE GENERATOR.",
        "intro": "Create QR codes for text or URLs and download PNG images for free, with no daily usage limits. No account required; encoding happens on your device.",
        "title": "Free QR Code Generator — Download PNG, No Sign-Up",
        "description": "Create QR codes for text or URLs and download PNG images for free, with no daily usage limits. No account required; encoding happens on your device.",
        "heading": "CREATE A QR CODE",
        "summary": "Encode text or a URL into a downloadable PNG. The generator supports Unicode text, multiple image sizes, and four error-correction levels.",
        "steps": ["Enter the exact text or destination URL.", "Choose an error-correction level.", "Select the output image size.", "Download the PNG and test it on more than one device."],
        "notes": [
            ("TEST BEFORE PUBLISHING", "A QR code can be technically valid while containing a mistyped address. Scan the final downloaded image and confirm the destination before printing or distributing it."),
            ("ERROR CORRECTION", "Higher correction can help a code remain readable after minor damage, but it makes the pattern denser and may increase the required QR version."),
        ],
        "faq": [
            ("Is QR content sent to the server?", "No. Encoding happens locally in the browser."),
            ("Can I enter Korean or other Unicode text?", "Yes. The generator supports Unicode text, including Korean characters."),
            ("Should I put confidential data in a QR code?", "No. Anyone who can scan a displayed QR code may read its contents."),
        ],
        "related": [],
    },
    "focus_timer": {
        "name": "Focus Timer",
        "h1": "FREE FOCUS TIMER.",
        "intro": "Use a free focus timer with 5, 15, 25 or 45-minute presets and custom durations. No account required; the countdown runs in your browser.",
        "title": "Free Focus Timer — 5, 15, 25 & 45 Minute Countdown",
        "description": "Use a free focus timer with 5, 15, 25 or 45-minute presets and custom durations. No account required; the countdown runs in your browser.",
        "heading": "USE THE FOCUS TIMER",
        "summary": "Run a distraction-free countdown for focused work, study, reading, or short breaks. Choose a preset or enter a custom duration up to 180 minutes.",
        "steps": ["Choose 5, 15, 25, 45 minutes or set a custom time.", "Select START FOCUS.", "Pause when needed or reset the current session.", "Keep the tab open to hear the optional completion sound."],
        "notes": [
            ("LOCAL TIMER STATE", "The current timer state can be stored in this browser so an accidental refresh does not immediately erase the session."),
            ("KEYBOARD CONTROLS", "Press Space to start or pause. Press R to reset when focus is not inside another control."),
        ],
        "faq": [
            ("What is the 25-minute preset for?", "It is a common focus interval, but you can choose any duration that fits your work."),
            ("Does the timer require an account?", "No. It runs in the browser without sign-in."),
            ("Will it work after I close the browser?", "The saved state may remain, but a closed browser cannot reliably play the completion sound."),
        ],
        "related": [],
    },
    "calculator": {
        "name": "Multi Calculator",
        "h1": "FREE ONLINE CALCULATOR.",
        "intro": "Calculate percentages, discounts, tax, tips and split bills for free, with no daily usage limits. No account required; calculations run in your browser.",
        "title": "Free Online Calculator — Percentage, Discount & Tips",
        "description": "Calculate percentages, discounts, tax, tips and split bills for free, with no daily usage limits. No account required; calculations run in your browser.",
        "heading": "EVERYDAY CALCULATIONS",
        "summary": "Use four focused calculator modes with visible formulas. Results update in the browser and can be copied without submitting the entered values.",
        "steps": ["Choose arithmetic, percentage, discount, or tip and split.", "Enter the requested values.", "Read the result and the displayed calculation summary.", "Copy the calculation and verify important totals against local rules."],
        "notes": [
            ("PERCENT, DISCOUNT AND TAX", "Percentage mode calculates a percent of a value or the change between two values. Discount mode removes the discount before applying the entered sales-tax rate."),
            ("GENERAL INFORMATION ONLY", "Taxability, service charges, tipping customs, and rounding rules vary. This calculator does not provide financial, tax, accounting, or legal advice."),
        ],
        "faq": [
            ("How is percentage change calculated?", "The difference between new and starting values is divided by the starting value and multiplied by 100."),
            ("Is tax applied before the discount?", "No. This tool applies the discount first and tax to the discounted subtotal."),
            ("Are calculator inputs uploaded?", "No. Calculations run in JavaScript in your browser."),
        ],
        "related": [],
    },
}
