"""Search-oriented, user-visible guides for each Browser Tools utility."""

TOOL_SEO = {
    "index": {
        "name": "Private PDF Merger",
        "title": "Merge PDF Files Locally and Privately — Browser Tools",
        "description": "Merge and reorder PDF files directly in your browser. Files stay on your device and the combined PDF downloads locally.",
        "heading": "HOW TO MERGE PDF FILES",
        "summary": "Combine two or more PDF documents in the order you choose. Processing happens in browser memory, so the source files are not uploaded to an application server.",
        "steps": ["Add at least two PDF files.", "Use the arrow controls to arrange the documents.", "Remove any file you do not want in the result.", "Select MERGE and save the downloaded PDF."],
        "notes": [
            ("LOCAL PDF PROCESSING", "The browser reads the selected documents and builds the new PDF on your device. Available memory, document size, and page count can affect processing time."),
            ("BEFORE YOU DELETE ORIGINALS", "Open the downloaded file and confirm its page order, orientation, links, forms, and visual quality. Keep backup copies of important source documents."),
        ],
        "faq": [
            ("Are my PDF files uploaded?", "No. This tool does not submit selected PDFs to an application upload endpoint."),
            ("Can I change the file order?", "Yes. Arrange the files in the queue before selecting MERGE."),
            ("Why can a large merge take longer?", "The work uses your device's processor and memory. Large or complex PDFs require more local resources."),
        ],
        "related": [("pdf_split", "SPLIT PDF"), ("pdf_organizer", "ORGANIZE PAGES"), ("pdf_to_images", "PDF TO IMAGES")],
    },
    "pdf_split": {
        "name": "Private PDF Splitter",
        "title": "Split PDF Pages Locally and Download a ZIP — Browser Tools",
        "description": "Preview PDF pages, choose exact cut points, and split a document locally in your browser. Download multiple results as a ZIP.",
        "heading": "HOW TO SPLIT A PDF",
        "summary": "See each page before choosing boundaries. A cut marker separates the pages on its left and right into different output documents.",
        "steps": ["Add one PDF file.", "Review the page thumbnails in reading order.", "Select the cut lines where a new document should begin.", "Choose SPLIT & DOWNLOAD ZIP and inspect the results."],
        "notes": [
            ("CHOOSE CUT POINTS CAREFULLY", "Cut controls appear at document boundaries and between pages. Clear or select all cuts when you need to reset the layout quickly."),
            ("PRIVATE BY DESIGN", "Previewing, splitting, and packaging happen locally. The source document is not stored by this site."),
        ],
        "faq": [
            ("Can I split a PDF into every page?", "Yes. Use SELECT ALL to place a cut between every page."),
            ("What does the ZIP contain?", "It contains the PDF sections created by your selected cut points."),
            ("Can encrypted PDFs be split?", "Password-protected or restricted documents may not open. Use a permitted, unlocked copy."),
        ],
        "related": [("index", "MERGE PDF"), ("pdf_organizer", "ORGANIZE PAGES"), ("pdf_to_images", "PDF TO IMAGES")],
    },
    "pdf_organizer": {
        "name": "PDF Page Organizer",
        "title": "Reorder, Rotate and Extract PDF Pages — Browser Tools",
        "description": "Organize PDF pages locally: reorder, rotate, remove, or select pages to extract into a new PDF without uploading the file.",
        "heading": "ORGANIZE PDF PAGES",
        "summary": "Edit the page sequence of one PDF before creating a new document. Page cards can be dragged, rotated, removed, or selected for extraction.",
        "steps": ["Add one PDF and wait for the thumbnails.", "Drag page cards into the required order.", "Rotate or remove pages as needed.", "Save all visible pages, or select pages and use EXTRACT SELECTED."],
        "notes": [
            ("SAVE OR EXTRACT", "SAVE PDF keeps every visible page in the displayed order. EXTRACT SELECTED creates a separate PDF containing only the pages you selected."),
            ("NON-DESTRUCTIVE WORKFLOW", "The original file is not overwritten. The organizer creates a new download so you can compare it with the source."),
        ],
        "faq": [
            ("Can I undo a removed page?", "There is no full undo history. Reload the source PDF if you remove a page by mistake."),
            ("Does rotation change the original?", "No. Rotation is applied only to the new downloaded PDF."),
            ("Can I combine several PDFs here?", "Use PDF Merge for multiple documents; this organizer works with one PDF at a time."),
        ],
        "related": [("index", "MERGE PDF"), ("pdf_split", "SPLIT PDF"), ("images_to_pdf", "IMAGES TO PDF")],
    },
    "pdf_to_images": {
        "name": "PDF to Image Converter",
        "title": "Convert PDF Pages to PNG or JPG Locally — Browser Tools",
        "description": "Convert selected PDF pages to PNG or JPEG images in your browser. Choose page ranges and download the images in a ZIP file.",
        "heading": "CONVERT PDF TO IMAGES",
        "summary": "Render an entire PDF or selected pages as PNG or JPEG files. Page-range controls help avoid processing pages you do not need.",
        "steps": ["Add one PDF.", "Enter a range such as 1-3, 5 or leave it blank for all pages.", "Choose PNG or JPEG and a rendering scale.", "Download the generated images as a ZIP."],
        "notes": [
            ("PNG OR JPEG", "PNG is useful for text, diagrams, and crisp edges. JPEG can produce smaller photographic files and offers an adjustable quality setting."),
            ("SCALE AND MEMORY", "A larger rendering scale creates more pixels and can improve detail, but it also increases file size, memory use, and processing time."),
        ],
        "faq": [
            ("Can I convert only one page?", "Yes. Enter that page number in the page-range field."),
            ("Why are the results in a ZIP?", "A ZIP keeps multiple page images together in one download."),
            ("Does this extract original embedded images?", "No. It renders each complete PDF page as an image."),
        ],
        "related": [("images_to_pdf", "IMAGES TO PDF"), ("pdf_organizer", "ORGANIZE PAGES"), ("image_toolkit", "IMAGE TOOLKIT")],
    },
    "images_to_pdf": {
        "name": "Images to PDF Converter",
        "title": "Convert JPG, PNG and WebP Images to PDF — Browser Tools",
        "description": "Arrange JPG, PNG, or WebP images and convert them into one PDF locally. Choose automatic, A4, or US Letter page sizes.",
        "heading": "CONVERT IMAGES TO PDF",
        "summary": "Turn a sequence of JPG, PNG, or WebP images into one downloadable PDF. Reorder the images and select how each image fits on its page.",
        "steps": ["Add one or more supported images.", "Arrange or remove image cards.", "Choose matched image pages, A4, or US Letter and set a margin.", "Select CREATE PDF and review the download."],
        "notes": [
            ("PAGE SIZE OPTIONS", "Match each image preserves its natural proportions. A4 and US Letter place images inside a consistent portrait page."),
            ("IMAGE QUALITY", "The tool places the selected image data into the new document. Very large images can create a large PDF and require more browser memory."),
        ],
        "faq": [
            ("Which image formats are supported?", "The file picker accepts JPEG, PNG, and WebP images."),
            ("Can every page use the image's own size?", "Yes. Choose Match each image."),
            ("Are my images uploaded?", "No. They are read and converted in your browser."),
        ],
        "related": [("pdf_to_images", "PDF TO IMAGES"), ("image_toolkit", "IMAGE TOOLKIT"), ("index", "MERGE PDF")],
    },
    "image_toolkit": {
        "name": "Image Resizer and Converter",
        "title": "Resize, Compress and Convert Images Locally — Browser Tools",
        "description": "Resize an image, adjust JPEG or WebP quality, and convert between JPG, PNG, and WebP directly in your browser.",
        "heading": "RESIZE AND CONVERT IMAGES",
        "summary": "Prepare one image for sharing, websites, documents, or storage. Set exact pixel dimensions and download it as JPEG, PNG, or WebP.",
        "steps": ["Add a JPG, PNG, or WebP image.", "Enter the required width or height.", "Keep the aspect ratio on unless you intentionally want stretching.", "Choose a format and quality, then process the download."],
        "notes": [
            ("FORMAT DIFFERENCES", "JPEG is widely compatible and efficient for photos. PNG preserves transparency and sharp graphics. WebP often balances quality and smaller file size in modern browsers."),
            ("TRANSPARENCY", "PNG and WebP can preserve transparent areas. JPEG has no alpha channel, so transparent pixels are placed on white."),
        ],
        "faq": [
            ("Does quality affect PNG?", "No. The quality slider applies to lossy formats such as JPEG and WebP; PNG output is lossless."),
            ("What does aspect ratio mean?", "It is the relationship between width and height. Locking it prevents accidental distortion."),
            ("Can I enlarge a small image?", "Yes, but enlargement cannot recreate detail that was not present in the source."),
        ],
        "related": [("images_to_pdf", "IMAGES TO PDF"), ("pdf_to_images", "PDF TO IMAGES"), ("qr_generator", "QR GENERATOR")],
    },
    "file_hash": {
        "name": "File Hash Checker",
        "title": "SHA-256, SHA-384 and SHA-512 File Hash Checker",
        "description": "Calculate a SHA-256, SHA-384, or SHA-512 checksum for a local file and compare its cryptographic fingerprint without uploading it.",
        "heading": "CHECK A FILE CHECKSUM",
        "summary": "Calculate a repeatable cryptographic fingerprint for any local file. Compare the result with a checksum published by a trusted source.",
        "steps": ["Choose the file you want to verify.", "Select SHA-256, SHA-384, or SHA-512.", "Wait for the hexadecimal hash to appear.", "Copy it and compare every character with the trusted reference."],
        "notes": [
            ("WHAT A MATCH MEANS", "A matching checksum supports the conclusion that your copy has the same bytes as the reference file. Even a one-byte change produces a different result."),
            ("NOT A MALWARE SCAN", "A hash does not inspect a file for malicious behavior and cannot prove that the publisher is trustworthy. Obtain reference hashes from an authoritative source."),
        ],
        "faq": [
            ("Which algorithm should I choose?", "Use the algorithm named by the file publisher. SHA-256 is a common modern default when a choice is available."),
            ("Is the selected file uploaded?", "No. The browser's cryptographic API reads it locally."),
            ("Why does my hash not match?", "The file may be incomplete, modified, a different version, or compared with the wrong algorithm."),
        ],
        "related": [("qr_generator", "QR GENERATOR"), ("image_toolkit", "IMAGE TOOLKIT"), ("content_page", "PRIVACY", {"slug": "privacy"})],
    },
    "qr_generator": {
        "name": "Private QR Code Generator",
        "title": "Create a Private QR Code for Text or URLs — Browser Tools",
        "description": "Generate and download a QR code for text or a URL directly in your browser. Choose error correction and image size without submitting the content.",
        "heading": "CREATE A QR CODE",
        "summary": "Encode text or a URL into a downloadable PNG. The generator supports Unicode text, multiple image sizes, and four error-correction levels.",
        "steps": ["Enter the exact text or destination URL.", "Choose an error-correction level.", "Select the output image size.", "Download the PNG and test it on more than one device."],
        "notes": [
            ("TEST BEFORE PUBLISHING", "A QR code can be technically valid while containing a mistyped address. Scan the final downloaded image and confirm the destination before printing or distributing it."),
            ("ERROR CORRECTION", "Higher correction can help a code remain readable after minor damage, but it makes the pattern denser and may increase the required QR version."),
        ],
        "faq": [
            ("Is QR content sent to the server?", "No. Encoding happens locally in the browser."),
            ("Can I enter Korean or other Unicode text?", "Yes. The generator supports Unicode text, including Korean characters."),
            ("Should I put confidential data in a QR code?", "No. Anyone who can scan a displayed QR code may read its contents."),
        ],
        "related": [("file_hash", "FILE HASH"), ("image_toolkit", "IMAGE TOOLKIT"), ("calculator", "CALCULATOR")],
    },
    "focus_timer": {
        "name": "Focus Timer",
        "title": "Free 5, 15, 25 and 45 Minute Focus Timer",
        "description": "Use a clean browser focus timer with quick presets, custom durations, pause, reset, sound, and locally saved timer state.",
        "heading": "USE THE FOCUS TIMER",
        "summary": "Run a distraction-free countdown for focused work, study, reading, or short breaks. Choose a preset or enter a custom duration up to 180 minutes.",
        "steps": ["Choose 5, 15, 25, 45 minutes or set a custom time.", "Select START FOCUS.", "Pause when needed or reset the current session.", "Keep the tab open to hear the optional completion sound."],
        "notes": [
            ("LOCAL TIMER STATE", "The current timer state can be stored in this browser so an accidental refresh does not immediately erase the session."),
            ("KEYBOARD CONTROLS", "Press Space to start or pause. Press R to reset when focus is not inside another control."),
        ],
        "faq": [
            ("What is the 25-minute preset for?", "It is a common focus interval, but you can choose any duration that fits your work."),
            ("Does the timer require an account?", "No. It runs in the browser without sign-in."),
            ("Will it work after I close the browser?", "The saved state may remain, but a closed browser cannot reliably play the completion sound."),
        ],
        "related": [("calculator", "CALCULATOR"), ("path_studio", "PATH STUDIO"), ("index", "MERGE PDF")],
    },
    "calculator": {
        "name": "Multi Calculator",
        "title": "Free Percentage, Discount, Tax, Tip and Split Calculator",
        "description": "Calculate arithmetic, percentages, percentage change, discounts, sales tax, tips, and split bills with visible formulas in your browser.",
        "heading": "EVERYDAY CALCULATIONS",
        "summary": "Use four focused calculator modes with visible formulas. Results update in the browser and can be copied without submitting the entered values.",
        "steps": ["Choose arithmetic, percentage, discount, or tip and split.", "Enter the requested values.", "Read the result and the displayed calculation summary.", "Copy the calculation and verify important totals against local rules."],
        "notes": [
            ("PERCENT, DISCOUNT AND TAX", "Percentage mode calculates a percent of a value or the change between two values. Discount mode removes the discount before applying the entered sales-tax rate."),
            ("GENERAL INFORMATION ONLY", "Taxability, service charges, tipping customs, and rounding rules vary. This calculator does not provide financial, tax, accounting, or legal advice."),
        ],
        "faq": [
            ("How is percentage change calculated?", "The difference between new and starting values is divided by the starting value and multiplied by 100."),
            ("Is tax applied before the discount?", "No. This tool applies the discount first and tax to the discounted subtotal."),
            ("Are calculator inputs uploaded?", "No. Calculations run in JavaScript in your browser."),
        ],
        "related": [("focus_timer", "FOCUS TIMER"), ("qr_generator", "QR GENERATOR"), ("file_hash", "FILE HASH")],
    },
    "path_studio": {
        "name": "Path Studio",
        "title": "Browser Bezier Path and Layer Editor — Path Studio",
        "description": "Draw selectable Bezier paths, edit anchors and handles, manage image layers, adjust opacity, and save local project files on desktop.",
        "heading": "DRAW EDITABLE BEZIER PATHS",
        "summary": "Path Studio is a desktop-only vector workspace for drawing curves, managing paths and image layers, and saving projects locally for later editing.",
        "steps": ["Open the tool on a screen at least 1080 pixels wide.", "Use PEN to place anchors and Alt-drag to create curve handles.", "Use SELECT to edit anchors, handles, images, or complete paths.", "Save a .pathwork project or export a flattened PNG."],
        "notes": [
            ("PATHS AND ENDPOINTS", "Open endpoints can be joined. Start and end markers change color on hover to make path closure and joining easier to identify."),
            ("LOCAL PROJECT FILES", "SAVE PROJECT downloads a local project containing editable path and image-layer data. Keep that file if you want to continue later."),
        ],
        "faq": [
            ("Why is Path Studio disabled on mobile?", "Its canvas, layer inspector, and precision controls require a desktop-width workspace."),
            ("How do I create a curve?", "With PEN active, hold Alt while dragging an anchor to create Bezier handles."),
            ("Can I change image opacity?", "Yes. Select an image layer and adjust its opacity in Properties."),
        ],
        "related": [("focus_timer", "FOCUS TIMER"), ("image_toolkit", "IMAGE TOOLKIT"), ("content_page", "FULL GUIDE", {"slug": "guides"})],
    },
}
